//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add failure!.
        /// </summary>
        public static string DevMsg_Fail {
            get {
                return ResourceManager.GetString("DevMsg_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add success!.
        /// </summary>
        public static string DevMsg_Success {
            get {
                return ResourceManager.GetString("DevMsg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bị trùng, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_Duplicated_Code {
            get {
                return ResourceManager.GetString("UserMsg_Duplicated_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khoản thu bị trùng, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_Duplicated_FeeName {
            get {
                return ResourceManager.GetString("UserMsg_Duplicated_FeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phạm vi thu bị trống, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_EmptyApplyObject {
            get {
                return ResourceManager.GetString("UserMsg_EmptyApplyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khoản thu bị trống, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_EmptyFeeName {
            get {
                return ResourceManager.GetString("UserMsg_EmptyFeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Kì thu bị trống &lt;=0, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_EmptyPeriod {
            get {
                return ResourceManager.GetString("UserMsg_EmptyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức thu  bị trống hoặc &lt;0 vui lòng kiểm tra lại .
        /// </summary>
        public static string UserMsg_EmptyPrice {
            get {
                return ResourceManager.GetString("UserMsg_EmptyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Đơn vị thu bị trống hoặc &lt;=0, vui lòng kiểm tra lại .
        /// </summary>
        public static string UserMsg_EmptyUnit {
            get {
                return ResourceManager.GetString("UserMsg_EmptyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA!.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thất bại.
        /// </summary>
        public static string UserMsg_Fail {
            get {
                return ResourceManager.GetString("UserMsg_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là bản thu hệ thống, bạn không được xóa.
        /// </summary>
        public static string UserMsg_isSystem {
            get {
                return ResourceManager.GetString("UserMsg_isSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm khoản thu không có, vui lòng nhập lại.
        /// </summary>
        public static string UserMsg_NoGroup {
            get {
                return ResourceManager.GetString("UserMsg_NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string UserMsg_Success {
            get {
                return ResourceManager.GetString("UserMsg_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string VIE_Gender_Name_Female {
            get {
                return ResourceManager.GetString("VIE_Gender_Name_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string VIE_Gender_Name_Male {
            get {
                return ResourceManager.GetString("VIE_Gender_Name_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định.
        /// </summary>
        public static string VIE_Gender_Name_Other {
            get {
                return ResourceManager.GetString("VIE_Gender_Name_Other", resourceCulture);
            }
        }
    }
}
